import { Author, Post } from './types';

export const authors: Author[] = [
  {
    id: 'author-1',
    name: 'Dr. Eleanor Vance',
    imageUrl: 'https://picsum.photos/seed/teacher1/100/100',
    bio: 'Eleanor holds a PhD in Linguistics and has over 15 years of experience in curriculum design for English language learners. She specializes in syntax and phonetics.',
  },
  {
    id: 'author-2',
    name: 'Leo Maxwell',
    imageUrl: 'https://picsum.photos/seed/teacher2/100/100',
    bio: 'Leo is a certified ESL instructor who has taught English in over ten countries. He is passionate about practical communication and helping students build confidence.',
  },
  {
    id: 'author-3',
    name: 'Jessica Miller',
    imageUrl: 'https://picsum.photos/seed/teacher3/100/100',
    bio: 'Jessica is a corporate communications coach with a background in international business. She helps professionals enhance their English for the global workplace.',
  },
];

export const posts: Post[] = [
  {
    id: '1',
    title: 'Mastering the Present Perfect Tense',
    excerpt: 'The present perfect is one of the trickiest tenses for English learners. This guide breaks it down with clear examples and exercises.',
    content: `Understanding when to use the present perfect versus the simple past is a common hurdle. The key difference lies in the connection to the present. We use the present perfect for actions that started in the past but are still relevant now, or for life experiences without a specific time.\n\nFor example, saying "I have lived in London" implies that this experience is part of your life story, whereas "I lived in London in 2010" refers to a finished period. This distinction is crucial for sounding natural.\n\nIn this article, we'll explore the structure (have/has + past participle), common adverbs used with it (like 'for', 'since', 'already', 'yet'), and practice scenarios to help you master this essential English tense.`,
    imageUrl: 'https://picsum.photos/seed/grammar/800/600',
    publishDate: 'October 26, 2024',
    authorId: 'author-1',
  },
  {
    id: '2',
    title: '10 Common English Idioms and How to Use Them',
    excerpt: 'Sound more like a native speaker by incorporating these common idioms into your vocabulary. We explain what they mean and how to use them naturally.',
    content: `Idioms are expressions where the meaning isn't obvious from the individual words. Using them correctly can make your English sound more fluent and natural. Let's look at a few popular ones.\n\n"Bite the bullet" means to face a difficult situation with courage. For example: "I hate going to the dentist, but I'll have to bite the bullet." Another one is "break the ice," which means to initiate a conversation in a social setting.\n\nThis post covers ten of the most frequent idioms, from "spilling the beans" to "hitting the nail on the head." We provide definitions, example sentences, and tips on the right context to use them in.`,
    imageUrl: 'https://picsum.photos/seed/conversation/800/600',
    publishDate: 'October 15, 2024',
    authorId: 'author-2',
  },
  {
    id: '3',
    title: 'A Practical Guide to Phrasal Verbs',
    excerpt: 'Phrasal verbs (e.g., "give up," "look after") are essential for everyday English. This guide provides tips and examples to help you learn them effectively.',
    content: `A phrasal verb is a verb combined with a preposition or adverb, creating a new meaning. For example, 'look' means to see, but 'look after' means to take care of someone. They are incredibly common in spoken English.\n\nThe challenge is that their meanings are often idiomatic and they can sometimes be separated. For example, you can say "turn the light on" or "turn on the light."\n\nWe'll categorize common phrasal verbs by topic (e.g., work, relationships) and provide clear examples to help you understand and start using them with confidence. Don't give up on learning them!`,
    imageUrl: 'https://picsum.photos/seed/books/800/600',
    publishDate: 'September 28, 2024',
    authorId: 'author-1',
  },
    {
    id: '4',
    title: 'How to Improve Your English Listening Skills',
    excerpt: 'Do you struggle to understand native speakers? These practical tips will help you train your ear and improve your comprehension.',
    content: `Listening is often the most challenging skill to develop. The key is active listening, not just passive hearing. Start by listening to materials you can mostly understand, like podcasts or TV shows for learners, and gradually increase the difficulty.\n\nDon't be afraid to use subtitles, but use them strategically. First, watch with English subtitles. Then, watch again without them. This helps connect the spoken words with their written form.\n\nAnother great technique is transcription. Listen to a short audio clip and try to write down exactly what you hear. This forces you to pay close attention to pronunciation, linked sounds, and intonation.`,
    imageUrl: 'https://picsum.photos/seed/listening/800/600',
    publishDate: 'September 12, 2024',
    authorId: 'author-2',
  },
  {
    id: '5',
    title: 'The Difference Between "Affect" and "Effect"',
    excerpt: 'These two words are commonly confused by learners and native speakers alike. We clarify the difference with simple rules and examples.',
    content: `The easiest way to remember the difference is that "affect" is almost always a verb, and "effect" is almost always a noun. "Affect" means to influence or produce a change in something. For example: "The weather will affect our plans."\n\n"Effect" is the result or consequence of an action. For example: "The new medicine had a positive effect on the patient."\n\nWhile there are rare exceptions, following this verb/noun rule will be correct over 95% of the time. This article covers those exceptions and provides a quiz to test your understanding of how to use affect and effect correctly.`,
    imageUrl: 'https://picsum.photos/seed/writing/800/600',
    publishDate: 'August 30, 2024',
    authorId: 'author-1',
  },
  {
    id: '6',
    title: 'Writing a Perfect Professional Email in English',
    excerpt: 'From the subject line to the closing, learn the key phrases and etiquette for writing clear, polite, and effective emails in a professional context.',
    content: `A well-written email can make a huge difference in your career. Start with a clear and concise subject line. For example, "Meeting Follow-Up: Project Plan" is much better than "hello."\n\nUse appropriate greetings, like "Dear Mr. Smith" for formal situations or "Hi Sarah" for informal ones. The body of the email should be well-organized and to the point. Use phrases like "I am writing to inquire about..." or "I would like to follow up on..."\n\nFinally, choose a professional closing, such as "Sincerely," "Best regards," or "Kind regards," followed by your name. We'll provide templates for various situations, including job applications, meeting requests, and information inquiries.`,
    imageUrl: 'https://picsum.photos/seed/business/800/600',
    publishDate: 'August 15, 2024',
    authorId: 'author-2',
  },
  {
    id: '7',
    title: 'Tips for Sounding More Like a Native Speaker',
    excerpt: 'Beyond grammar and vocabulary, mastering pronunciation, intonation, and rhythm is key to fluency. Here are some tips to help you sound more natural.',
    content: `Perfect grammar is great, but prosody—the rhythm and intonation of speech—is what often separates intermediate learners from advanced speakers. Pay attention to sentence stress. In English, we stress content words (nouns, verbs, adjectives) more than function words (prepositions, articles).\n\nAlso, work on connected speech. Native speakers often link words together. For example, "an apple" sounds more like "anapple." Shadowing is a great technique to practice this: listen to a native speaker and repeat what they say exactly, trying to imitate their rhythm and pitch.\n\nThis article explores these concepts with audio examples to guide your practice.`,
    imageUrl: 'https://picsum.photos/seed/pronunciation/800/600',
    publishDate: 'July 22, 2024',
    authorId: 'author-1',
  },
  {
    id: '8',
    title: 'Vocabulary Building: Beyond the Flashcards',
    excerpt: 'Memorizing lists of words is not enough. Learn how to truly acquire new vocabulary by understanding context, collocations, and word families.',
    content: `To move a word from your passive vocabulary (words you recognize) to your active vocabulary (words you use), you need to engage with it in multiple ways. Don't just learn "happy." Learn its synonyms (joyful, cheerful, delighted), its antonyms (sad, miserable), and its different forms (happiness, happily).\n\nPay attention to collocations—words that often go together. We "make a mistake," not "do a mistake." Reading extensively is one of the best ways to see words in their natural context.\n\nThis guide offers several strategies, including using vocabulary notebooks, learning word roots, and using apps that focus on contextual learning, to help you build a richer and more usable vocabulary.`,
    imageUrl: 'https://picsum.photos/seed/vocabulary/800/600',
    publishDate: 'July 5, 2024',
    authorId: 'author-2',
  },
  {
    id: '9',
    title: 'The Ultimate Guide to Business English Communication',
    excerpt: 'Elevate your career with this comprehensive course on professional English. Master emails, presentations, negotiations, and networking in a business context.',
    content: `Effective communication is the cornerstone of success in the global business world. This course is designed to give you the language and skills you need to communicate with confidence and precision.\n\nModule 1: Professional Email Writing. Learn to write clear, concise, and polite emails for any situation, from inquiries to follow-ups.\n\nModule 2: Engaging Presentations. Discover techniques to structure and deliver compelling presentations that hold your audience's attention.\n\nModule 3: The Language of Negotiations. Equip yourself with the phrases and strategies to navigate negotiations effectively and achieve your objectives.\n\nModule 4: Networking with Confidence. Master small talk and build meaningful professional relationships with international colleagues and clients.\n\nEach module includes practical examples, downloadable templates, and interactive quizzes to solidify your learning. By the end of this course, you will not only have improved your English but also gained a powerful tool for career advancement.`,
    imageUrl: 'https://picsum.photos/seed/business-course/800/600',
    publishDate: 'November 01, 2024',
    authorId: 'author-3',
  },
];